# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: php:7.4-apache
      env:
        APACHE_DOCUMENT_ROOT: /var/www/html/drupal/docroot
      ports: [80]
#    strategy:
#      matrix:
#        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
#        node-version: [14.x, 16.x, 18.x]
    steps:
      - uses: actions/checkout@v3

      - name: Install Composer
        run: |
          /bin/sh ./drupal/install-composer.sh
          ./composer.phar --version

      - name: Copy Drush configuration
        run: |
          mkdir $HOME/.drush
          cp ./drupal/drush.yml $HOME/.drush

      - run: ./composer.phar create-project acquia/drupal-recommended-project /var/www/html/drupal

#      - name: Use Node.js ${{ matrix.node-version }}
#        uses: actions/setup-node@v3
#        with:
#          node-version: ${{ matrix.node-version }}

#      - run: yarn install --frozen-lockfile
#      - run: yarn prettier --check .
#      - run: yarn run lint
#      - name: Create Acquia CMS project
#        run: composer create-project acquia/drupal-recommended-project acms
#      - name: Install Acquia CMS with demo content, and start web server
#        run: |
#          ./vendor/bin/acms acms:install acquia_cms_headless --no-interaction
#          composer require drupal/acquia_cms_starter
#          ./vendor/bin/drush pm:enable acquia_cms_starter --yes
#          ./vendor/bin/drush serve --quiet 8080 &
#          sleep 2
#        working-directory: acms
#      - run: curl --fail http://127.0.0.1:8080/jsonapi
